### ISSUE TITLE
How to set-cookie in edge function

### ISSUE THREAD

**Issue by y0zong** [supabase/functions-relay#1]
https://github.com/supabase/functions-relay/blob/d6dba0efc708e495a5c2463e569c36415b676501/src/index.ts#L50
I don't know any other details about cookie implementation in edge system but it's seems all filtered from here, so how to set cookie in edge function?

**Comment by inian** [comment]
This has been disabled for security reasons. Since functions across all our customers are under the same subdomain, allowing setting cookies between them could be dangerous. Our domains are under the public suffix list, but we wanted to err on the side of caution. 

Can you send the cookie via a different header and having client side JS set the cookie instead?

**Comment by y0zong** [comment]
> Since functions across all our customers are under the same subdomain, allowing setting cookies between them could be dangerous

it make sense, I close this issue
